import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions | CheckCGPA — Engineering CGPA Calculator",
  description: "Terms and conditions for using CheckCGPA educational grading tools, estimation calculators, and percentage converters.",
  alternates: {
    canonical: "/terms-conditions",
  },
  openGraph: {
    title: "Terms & Conditions | CheckCGPA",
    description: "Terms and conditions for using CheckCGPA educational grading tools.",
    url: "/terms-conditions",
    type: "website",
  },
};

export default function TermsConditions() {
  return (
    <div className="w-full max-w-3xl mx-auto px-4 sm:px-6 pt-6 pb-4 sm:py-12 sm:pb-24">
      <Link href="/" className="inline-flex items-center text-sm font-medium text-foreground/60 hover:text-foreground mb-8 transition-colors">
        <ArrowLeft size={16} className="mr-2" />
        Back to Calculator
      </Link>
      
      <h1 className="text-4xl font-black mb-8">Terms & Conditions</h1>
      
      <div className="prose prose-invert max-w-none text-foreground/80 space-y-6">
        <p>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
        
        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">1. Acceptance of Terms</h2>
        <p>
          By accessing and using this calculator, you accept and agree to be bound by the terms and provision of this agreement.
        </p>

        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">2. Use License</h2>
        <p>
          This tool is provided for educational and informational purposes only. It is designed to help students estimate their SGPA, CGPA, and percentages based on publicly available university grading schemas.
        </p>

        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">3. Disclaimer of Accuracy</h2>
        <p>
          While we strive for 100% accuracy, this calculator is not an official university tool. The results generated by this website should be considered estimates. Always refer to your official university marks card and administration for your official, verified grades and percentages. We are not liable for any discrepancies.
        </p>

        <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">4. Limitations</h2>
        <p>
          In no event shall the creators of this website be liable for any damages (including, without limitation, damages for loss of data or profit) arising out of the use or inability to use the materials on this website.
        </p>
      </div>
    </div>
  );
}
